/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JavaNetbeans_mysql_Conn;

import com.libmgr.dao.DbHelper;
import java.sql.*;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/**
 *
 * @author simonbassey
 */
public class BookListScreen extends javax.swing.JInternalFrame {

    /**
     * Creates new form BookListScreen
     */
    public BookListScreen() {
        initComponents();
        
        displayBooks();
    }
    

    
    private void displayBooks(){
        try {
            String booksQuery = "select * from books";
            var booksResultSet = DbHelper.executeQuery(booksQuery);
            
            

            Vector<Vector<?>> tableData = new Vector<>();
            //result.getInt(""), result.getString("BookName"), result.getString("ISBN"), result.getString("AuthorName"), result.getString("pubDate"));
            while (booksResultSet.next()) {
                    Vector<Object> row = new Vector<>();
                    row.add(booksResultSet.getInt("bookId"));
                    row.add(booksResultSet.getString("BookName"));
                    row.add(booksResultSet.getString("AuthorName"));
                    row.add(booksResultSet.getString("ISBN"));
                    row.add(booksResultSet.getString("pubDate"));
                    
                    tableData.add(row);
                }
           Vector<String> columns = new Vector<>();
           columns.add("Id");
           columns.add("Title");
           columns.add("Autor");
           columns.add("ISBN");
           columns.add(("Pub. Date"));
                TableModel tableModel = new DefaultTableModel(tableData,columns);
                jTable1.setModel(tableModel);
            
            
        } 
        catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error occured +"+e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("All Books");
        setToolTipText("");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Title", "Author", "ISBN", "Pub. Date"
            }
        ));
        jTable1.setShowGrid(false);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 727, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
