/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JavaNetbeans_mysql_Conn;

import com.libmgr.dao.DbHelper;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class bookUpdateScreen extends javax.swing.JInternalFrame {

    /**
     * Creates new form bookUpdateScreen
     */
    public bookUpdateScreen() {
        initComponents();
        btnUpdate.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        bookName = new javax.swing.JTextField();
        authorNameField = new javax.swing.JTextField();
        isbnField = new javax.swing.JTextField();
        pubDateField = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(35, 35, 35))
        );

        jLabel1.setText("ID");

        jLabel2.setText("Bookname");

        jLabel3.setText("Authorname");

        jLabel4.setText("ISBN");

        jLabel5.setText("pubDate");

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdate)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(idField)
                        .addComponent(bookName)
                        .addComponent(authorNameField)
                        .addComponent(isbnField)
                        .addComponent(pubDateField, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(bookName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(authorNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(isbnField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(pubDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btnUpdate))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public BookModel Searchbook(String searchText){
        try{
            String query = "select * from books where BookName like ? or AuthorName like ? or ISBN = ? or pubDate like ? or bookId = ?";
        Connection connect = DbHelper.getConnection("");
            PreparedStatement statement = connect.prepareStatement(query);
            
            statement.setString(1, "%"+searchText+"%");
            statement.setString(2, "%"+searchText+"%");
            statement.setString(3, "%"+searchText+"%");
            statement.setString(4, "%"+searchText+"%");
            statement.setInt(5, convertToInt(searchText));
            
            ResultSet result = statement.executeQuery();
            BookModel bookFound = new BookModel();
            while(result.next()){
                bookFound.setBookName(result.getString("BookName"));
                bookFound.setAuthorName(result.getString("AuthorName"));
                bookFound.setIsbn(result.getString("ISBN"));
                bookFound.setpubDate(result.getString("pubDate"));
                bookFound.setId(result.getInt("bookId"));
                break;
            }
                return bookFound;
            
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Error occured while searching book");
            return null;
        }
        
        
    
}
    public Integer convertToInt(String Id){
        try{
           int identered = Integer.parseInt(Id);
           return identered;
        }
        catch(NumberFormatException e){
        return -1;
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //searchbook b = new searchbook();
        var searchTxt = jTextField1.getText();
        BookModel bookFound = Searchbook(searchTxt);
       ResultSet  result = null;
        try{
        if(bookFound != null){
              idField.setText(bookFound.getId()+"");
              bookName.setText(bookFound.getBookName());
              authorNameField.setText(bookFound.getAuthorName());
              isbnField.setText(bookFound.getIsbn());
              pubDateField.setText(bookFound.getpubDate());
              btnUpdate.setEnabled(true);
        } else{
            JOptionPane.showMessageDialog(null, "No data for this Id");
        }
      }catch(Exception e){
          JOptionPane.showMessageDialog(null, e.getMessage());
      }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
           /* String booksQuery = "delete from books where books.bookId = id";
            var booksResultSet = DbHelper.executeQuery(booksQuery); */
            //String id;
            //id = JOptionPane.showInputDialog("Enter book Id");
            
        String bookName = this.bookName.getText();
        String authorName = authorNameField.getText();
        String Isbn = this.isbnField.getText();
        String pubdate = pubDateField.getText();
          String Id =  idField.getText();
          Connection connect = DriverManager.getConnection("jdbc:mysql://localhost:3306/connector1?ServerTimeZone=UTC", "root","BillonaireConfi1");
         // Connection connect =DBHelper.getConnection();
          String booksUpdate = "update books set BookName = ?, AuthorName = ?, ISBN = ?, pubDate = ? where bookId =?";
            PreparedStatement state = connect.prepareStatement(booksUpdate);
       
            //    System.out.println("preparedStatement before binding = "+ state.toString());
           
           state.setString(1, bookName);
           state.setString(2,authorName);
           state.setString(3, Isbn);
           state.setString(4, pubdate); 
           state.setInt(5, Integer.parseInt(Id));
            
            int rows_affected = state.executeUpdate();
            if(rows_affected<0){
                JOptionPane.showMessageDialog(this,"Update Failed");   
            }else{
                JOptionPane.showMessageDialog(this, "Book Update successful");
            }
        }catch(Exception exception){
                System.out.println( exception);
        }

// TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField authorNameField;
    private javax.swing.JTextField bookName;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JTextField idField;
    private javax.swing.JTextField isbnField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField pubDateField;
    // End of variables declaration//GEN-END:variables
}
